# Generated by Django 2.0.5 on 2018-08-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, verbose_name='用户名')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号码')),
                ('car_number', models.CharField(max_length=100, unique=True, verbose_name='车牌号码')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('car_state', models.CharField(choices=[('dj', '待检测'), ('jc', '检测中'), ('yj', '已检测')], default='dj', max_length=10, verbose_name='汽车状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '车辆信息',
                'verbose_name_plural': '车辆信息',
            },
        ),
    ]
